### ISSUE TITLE
The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.

### ISSUE THREAD

**Issue by DevKuLT** [ribthegreat99OrN0P/Agile.NET-Deobfuscator#2]
Currently decompiling a file with Agile 6.6 with both string encryption & CSVM enabled. This is the process I've used so far:

-JitDumper 3 ran natively on a Windows 8 machine with NetBox as a framework substitute with 'Dump MD' checked.
-SAE with String & Flow with 'string delegates' checked.
-de4dot
-This tool

When using this tool, however, this error message shows up:
![image](https://user-images.githubusercontent.com/56172613/95692838-962ad700-0bdd-11eb-849d-a7a327808239.png)

Any input would be appreciated.

**Comment by ribthegreat99OrN0P** [comment]
Hello, all those steps are not needed. All you need todo is use my tool you do not need to use SAE and de4dot.

**Comment by ribthegreat99OrN0P** [comment]
Hello, all those steps are not needed (except for jitdumper). All you need to-do is use my tool. You do not need to use SAE and de4dot.

**Comment by DevKuLT** [comment]
So use just JitDumper then the tool and that removes CSVM?

**Comment by DevKuLT** [comment]
Mainly on 6.6 specifically. I tried this on 6.4 and it does work but on 6.6 it does not work for some reason

**Comment by digitalmedia34** [comment]
@imnotanotherdev did you find the solution?

**Comment by 0x14307** [comment]
Could not find a direct fix to this
