### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by jurypastes** [ribthegreat99OrN0P/Agile.NET-Deobfuscator#3]
![image](https://user-images.githubusercontent.com/70300189/97112366-a608e780-16c2-11eb-9e20-eea7e630f2f7.png)

Thats it lol

**Comment by DeclanFrampton** [comment]
> ![image](https://user-images.githubusercontent.com/70300189/97112366-a608e780-16c2-11eb-9e20-eea7e630f2f7.png)
> 
> Thats it lol

Can you provide more detail so I can reproduce the issue?

**Comment by DevKuLT** [comment]
What version of Agile was used?

**Comment by ribthegreat99OrN0P** [comment]
Hello, i cannot help you if you do not provide any information

**Comment by Maverick1983** [comment]
You use visual studio and create debug x86. On my exe work with 32-bit exe to Deobfuscate
