### ISSUE TITLE
Lost resource

### ISSUE THREAD

**Issue by Maverick1983** [ribthegreat99OrN0P/Agile.NET-Deobfuscator#4]
exe work, but lost all resource like image, icon, ecc...

UPDATE
This method lost resource ProxyDelegatesModule.cs

**Comment by ribthegreat99OrN0P** [comment]
Can you please specify what resource/image/icon you are losing? You shouldn't be losing any of them

**Comment by Maverick1983** [comment]
Yes, any.

Il Sab 7 Nov 2020, 15:37 ribthegreat99OrN0P <notifications@github.com> ha
scritto:
