### ISSUE TITLE
Agile 6.6 opcode virtualization

### ISSUE THREAD

**Issue by Maverick1983** [ribthegreat99OrN0P/Agile.NET-Deobfuscator#6]
Hi,
version 6.6 changed the function for creating methods to ":: dau". In case of virtualized code, (no code in the .exe but Agile becomes the JIL to retrieve the code at runtime of the executable), do you know how to do it?

**Comment by digitalmedia34** [comment]
do you have an example?

**Comment by Maverick1983** [comment]
> do you have an example?

[Roulette Tracker 7.18.zip](https://github.com/ribthegreat99OrN0P/Agile.NET-Deobfuscator/files/5792767/Roulette.Tracker.7.18.zip)
