### ISSUE TITLE
A debugger has been found running on your system

### ISSUE THREAD

**Issue by sleepymatto** [ribthegreat99OrN0P/Agile.NET-Deobfuscator#7]
Hello

I'm receiving the following error. Any suggestions? 
<img width="679" alt="Screenshot 2021-01-20 203606" src="https://user-images.githubusercontent.com/62895862/105276706-3db19100-5b5f-11eb-9f63-f365309d06e6.png">

**Comment by ribthegreat99OrN0P** [comment]
Just close the debugger
