### ISSUE TITLE
no error but nothing deobfuscated

### ISSUE THREAD

**Issue by Rayan113** [ribthegreat99OrN0P/Agile.NET-Deobfuscator#9]
Nothing did obfuscate aafter i did run the x64 release version of this deobfuscator.

![image](https://user-images.githubusercontent.com/61509305/116015400-5dae9000-a639-11eb-9302-ab41c4b8169d.png)
![image](https://user-images.githubusercontent.com/61509305/116015463-a2d2c200-a639-11eb-91f2-45d2bbc7b431.png)

**Comment by usdogu** [comment]
+1 same issue

**Comment by NotWaterScriptNhttp** [comment]
The word deobfuscator is not for the whole program like namespaces or class names, var names most of the time its just the code because the names are mostly made random

**Comment by ribthegreat99OrN0P** [comment]
Program cannot recover names for types, methods, namespaces, locals, fields, etc.....
